FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:sid

ENV DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket

RUN install_packages wget jq openjdk-24-jre-headless

COPY . /

COPY start.sh /usr/src/

RUN chmod +x /usr/src/start.sh

CMD [ "/bin/bash", "/usr/src/start.sh" ]
